# Generated by Django 2.2.16 on 2022-06-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220626_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin')], default='user', help_text='Выберете роль пользователя', max_length=10, verbose_name='Роль пользователя'),
        ),
    ]
