# Generated by Django 2.2.16 on 2022-06-26 23:03

from django.db import migrations


def change_fields_to_name(apps, shema_editor):
    User = apps.get_model('users', 'User')
    values = {
        1: 'user',
        2: 'moderator',
        3: 'admin'
    }
    for key in values.keys():
        User.objects.filter(role=key).update(role=values[key])

def restore_from_names(apps, shema_edtor):
    User = apps.get_model('users', 'User')
    values = {
        'user': 1,
        'moderator': 2,
        'admin': 3,
    }
    for key in values.keys():
        User.objects.filter(role=key).update(role=values[key])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220626_2301'),
    ]

    operations = [
        migrations.RunPython(change_fields_to_name, restore_from_names)
    ]
